[build]
  command = "cp -r dist/* . && cp trained_model_lite.pkl . && cp airport_encoder_lite.pkl . && cp -r utils . && cp -r data ."
  functions = "netlify/functions"
  publish = "."

[functions]
  python_runtime = "3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
